### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by wdecoster**
This PR has a couple of smaller fixes, of which some are related to comments from reviewers.

Specifically:

- I changed slightly how the color scale plotting of log likelihood ratios is done, including some scaling and refactoring to plot everything at once rather than per read 
- I added a file sniffer that returns the type of input files (needs to be extended in the future). This results in changes in the "date_type" variable which have been propagated to the rest of the code.
- Nanopolish data is now extracted in its own function - a placeholder is already provided for nanocompore which will be the subject of a next PR
- The axis of the nanopolish_calls is changed to mention "reads". 
- A colorscale is added to the nanopore_call data type plots (modification probability)

Do you have comments about the changes here @endrebak ?

### CODE REVIEW

**Comment by endrebak** [comment]
```  
  df = df.drop(columns=["Chromosome", "Score", "Strand"], errors='ignore')
```

I call `unstrand()` before this line so it will never contain a Strand column :) Otherwise it looks fine :)

**Comment by wdecoster** [comment]
Could it be that unstrand sets strand to `.` but doesn't actually drop it from the dataframe? Because that's what it looks like here.

**Comment by endrebak** [comment]
I cannot reproduce, but just keep it as is. Does not hurt :)

**Comment by endrebak** [comment]
You found a bug. If the pr was unstranded but contained a strand column, the strand column was not dropped. Thanks!

**Comment by wdecoster** [comment]
Ah, accidental finding then. I'll leave it as such now, doesn't hurt indeed, and we can still change it when your bug fix is out.

**Pull request merged**
