### PR TITLE
Update differential modification

### PR DESCRIPTION
**Pull request by endrebak**
- require pyranges setup.py
- allow user to run differential_modification from command line
- make very fast
- allow writing to file or stdout

### CODE REVIEW

**Comment by wdecoster** [comment]
Just curious, what's your reason to prefer subprocess for mkdir over [pathlib Path.mkdir()](https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir) from the standard library?

**Comment by endrebak** [comment]
I used to write py2.7 and 3-compatible code for a long time. No point anymore when I think about it :)

Good point!

**Comment by endrebak** [comment]
I'll update this PR with tests tomorrow :)

**Comment by wdecoster** [comment]
Feel free to add yourself to a "contributors" section in the README - really appreciate your help!

**Comment by endrebak** [comment]
I do not need it, but I guess it is a good way to make people more willing to contribute. So will do.

The most important thing is to cite the pyranges paper if that is the library you decide to go with :)

If you need any more genomics help, feel free to ask. It is probably easy for me since I have spent so much time doing it (in pandas/pyranges).

**Comment by wdecoster** [comment]
Credit where credit is due. And I cite pyranges in my preprint ;-)

**Comment by wdecoster** [comment]
By the way, `allele_specific_modification.py` does something very similar to `differential_modification.py`, only focussing on a simpler case of a 1 vs 1 comparison. The same improvements can probably be made in both scripts. The differential_modification script would eventually need better stats handling when comparing groups of samples, but for now I've just implemented this as a simple fisher exact test, which does suffice for within sample allele_specific_modification but is not optimal for across multiple samples differential_modification...

**Comment by endrebak** [comment]
Okay. Might the stuff you need in differential modification be generally useful to many people? If so I might implement it in pyranges. But I am not a stats buff, so you would need to tell me what exactly you want.

Here is one multi-comparison statistics function: https://biocore-ntnu.github.io/pyranges/statistics-computing-the-matthews-correlation-coeficcient-between-ranges.html

The example uses only two pyranges though.

**Comment by endrebak** [comment]
I have reorganized the library slightly to make more testable. Feel free to tell me to change stuff if you want it some other way. I am not completely done yet though.

**Comment by wdecoster** [comment]
It's not how I usually structure my repo, but it makes sense so I have no objections. Let me know when you think you're done and I'll go over things in more detail.

**Comment by endrebak** [comment]
I think it should be working now. Feel free to have a look. I'll do the other stuff on a different branch I guess :)

**Comment by wdecoster** [comment]
Thanks! I'll try to check out the changes tomorrow.

**Comment by endrebak** [comment]
Do not merge yet please. I need to think about whether the two first joins should have been outer too :)

**Comment by wdecoster** [comment]
Going through your code now and everything looks great. Is there a reason you reassign things like `cutoff = args.cutoff` and `f = args.out`?

**Comment by endrebak** [comment]
Often I need to use variables more than once. Then `cutoff` is more pleasant to write than `args.cutoff`. But I can change it to args.cutoff if you prefer.

Also, if you use many variables from args in a func call then the code might become noisy:

```
func(args.bed, args.m1, args.m2, args.cutoff)
```

is harder to read than

```
func(bed, m1, m2, cutoff)
```

But this is just something I was doing unconsciously and do not care much about. Feel free to tell me to change it :)

**Comment by endrebak** [comment]
Also, if you feel methplotlib is getting mature you might want to advertise it on biostars also :)

**Comment by wdecoster** [comment]
Oh good, I may unconsciously clean up things like that later. I agree it's more pleasant to write but with tab completion (at least in my editor) that's not so much of an issue.

Thanks for adding the FDR too! I think this can be merged, I'll just wait until my latest changes pass the test...

> Also, if you feel methplotlib is getting mature you might want to advertise it on biostars also :)

Good idea, I will do that sooner or later.

**Comment by wdecoster** [comment]
For the record, after merging I (and my code editor) have made some changes regarding removing unnecessary imports, some of those reassignments I mentioned and there were a couple of lines which were now too long (I use a max length of 100). I've also bumped the version and will push out an update to PyPI if it passes the tests.

If you have any more ideas on how to improve this I'd love to hear it. I absolutely don't mind including you on the paper if you would want to, but I'll have to see how the review process goes.

**Comment by endrebak** [comment]
I would love that, perhaps I can help you answer reviewer comments or something :)

Feel free to format/modify the code however you want to, of course :) It is your project :)

**Comment by endrebak** [comment]
I could also help you speed up things (if that is needed - I do not work with methylation myself, so I have no idea :) ) and write docs/tests.

**Comment by wdecoster** [comment]
I'll keep you posted. 

Things are reasonably fast currently, so it's not really worth spending lots of time on improving it. I'd be happy to learn from you if you see things which can be faster.
Also, there are things in the main methplotlib visualization scripts that I wrote before I stumbled upon pyranges. There are some nasty things in there (e.g. parsing a gtf) that I still want to improve (in annotation.py). It's working fine the way it's now, therefore, it's not such a high priority for me to get back to that, but if you feel like playing with that then I wouldn't mind at all.

**Comment by endrebak** [comment]
Cool :) I'd love to look into it just to understand how people use
pyranges. Will look at Monday

**Comment by wdecoster** [comment]
Well, those are parts where I should have used pyranges but didn't know it existed yet :-/

**Pull request merged**
